language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: pfinal-isi
  api_key:
    secure: Wb7WboOsyC8P+YAIzblYQAb25I3TEgxUkcEAKWMrgQMOrEGqdd++A20wXq5mI2dqkOR4F2GByYUFQhxd8OpBMMAFgo/Bgq4ujAP7twCwmll3wRVN87vkPaQuYfTFkhLiOHMesjufiF3qWh7BXjZPkOOxK6SM1lbwyF5zcK8zkp1mNIw8wcaOFUnynBvCiAbzMiqnGAD+jEiCBDHfameHdt00IPuj3SCMgKvzsCkZjIHehSmQLjAwpsp8M3IpztnOH89pojae4iyax5jNRKBakK0SbFec9an7WGSlt6iuEMZLKnvrucjI3XHYBx6koQKEorphuoyUT/xOV05tv2DoHEbQqhc12Nmw8N2ujlCXXCdSuO+nke+7TY8m/p9qmBVQpFK66xDOc35CEJhnj2DLgxdCtJgDfMqTfD3xAoC4zwPS2+vlD68sphY9WCmNrILBDus1LNxZwQ1ztyHvvtMXYl/+Yu2kG8h+YiG0eAPa2UYEFhG1WOYj730aMzo6g80O1bKDPvU6Wq6vrW7vw9nzrUdswBE9W3ymQxPuWMJDZ9fjSgv2VWs0Esd3FuSGPEym+rNjtwaoxF2tItzdMwQkUV1zxX+JmCtfkm9UQwsjQn/ufLXse/mbbySsnlFbae7uKH4DgGhVYyHYwZOkbjszaJcNX0MuErdyNmBUc+uKgzM=
